"""add articles.source_name

Revision ID: 447dea3e2f06
Revises: eeeb1c972307
Create Date: 2026-08-17 13:34:31.914943
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '447dea3e2f06'
down_revision: Union[str, None] = 'eeeb1c972307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_name', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('source_name')

    # ### end Alembic commands ###
