"""initial schema

Revision ID: eeeb1c972307
Revises: 
Create Date: 2026-08-17 02:48:10.024536
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eeeb1c972307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('redistributable', sa.Boolean(), nullable=False),
    sa.Column('body_paragraphs', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scroll_position', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('start_paragraph_idx', sa.Integer(), nullable=False),
    sa.Column('start_word_idx', sa.Integer(), nullable=False),
    sa.Column('end_paragraph_idx', sa.Integer(), nullable=False),
    sa.Column('end_word_idx', sa.Integer(), nullable=False),
    sa.Column('surface_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('reading_sessions')
    op.drop_table('articles')
    op.drop_table('users')
    # ### end Alembic commands ###
